
import { ListOfCity } from "../../constant/ListOfCity";
import { ListOfEventAchiever } from "../../constant/ListOfEventAchiever";

import saphireAchievers1 from "../../assets/images/saphireAchiever/saphireAchievers1.png";
import saphireAchievers2 from "../../assets/images/saphireAchiever/saphireAchievers2.png";
import saphireAchievers3 from "../../assets/images/saphireAchiever/saphireAchievers3.png";
import saphireAchievers4 from "../../assets/images/saphireAchiever/saphireAchievers4.png";
import saphireAchievers5 from "../../assets/images/saphireAchiever/saphireAchievers5.png";
import saphireAchievers6 from "../../assets/images/saphireAchiever/saphireAchievers6.png";
import saphireAchievers7 from "../../assets/images/saphireAchiever/saphireAchievers7.png";
import saphireAchievers8 from "../../assets/images/saphireAchiever/saphireAchievers8.png";
import saphireAchievers9 from "../../assets/images/saphireAchiever/saphireAchievers9.png";
import saphireAchievers10 from "../../assets/images/saphireAchiever/saphireAchievers10.png";
import saphireAchievers11 from "../../assets/images/saphireAchiever/saphireAchievers11.png";
import saphireAchievers12 from "../../assets/images/saphireAchiever/saphireAchievers12.png";
import saphireAchievers13 from "../../assets/images/saphireAchiever/saphireAchievers13.png";
import saphireAchievers14 from "../../assets/images/saphireAchiever/saphireAchievers14.png";
import saphireAchievers15 from "../../assets/images/saphireAchiever/saphireAchievers15.png";
import saphireAchievers16 from "../../assets/images/saphireAchiever/saphireAchievers16.png";
import saphireAchievers17 from "../../assets/images/saphireAchiever/saphireAchievers17.png";
import saphireAchievers18 from "../../assets/images/saphireAchiever/saphireAchievers18.png";
import saphireAchievers19 from "../../assets/images/saphireAchiever/saphireAchievers19.png";
import saphireAchievers20 from "../../assets/images/saphireAchiever/saphireAchievers20.png";
import saphireAchievers21 from "../../assets/images/saphireAchiever/saphireAchievers21.png";
import saphireAchievers22 from "../../assets/images/saphireAchiever/saphireAchievers22.png";
import saphireAchievers23 from "../../assets/images/saphireAchiever/saphireAchievers23.png";
import saphireAchievers24 from "../../assets/images/saphireAchiever/saphireAchievers24.png";
import saphireAchievers25 from "../../assets/images/saphireAchiever/saphireAchievers25.png";
import saphireAchievers26 from "../../assets/images/saphireAchiever/saphireAchievers26.png";
import saphireAchievers27 from "../../assets/images/saphireAchiever/saphireAchievers27.png";


export const SapphireWinners = [
    {
        name: "Ann Shereen Yao",
        image: saphireAchievers1,
        country: ListOfCity.JKT,
        YoutubeLink: "https://www.youtube.com/watch?v=is5ie02NnyA&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2025UPCOMING"], ListOfEventAchiever["2023CLASSICJKT"]]
    },
    {
        name: "Clarissa Stefanny",
        image: saphireAchievers2,
        country: ListOfCity.PNT,
        YoutubeLink: "https://www.youtube.com/watch?v=XR8yYVUsBzo&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2025UPCOMING"]]
    },
    {
        name: "Cathleen Scarlett Hayasi",
        image: saphireAchievers3,
        country: ListOfCity.JKT,
        YoutubeLink: "https://www.youtube.com/watch?v=D1ct_m0XJtY&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2025UPCOMING"], ListOfEventAchiever["2023CLASSICJKT"]]
    },
    {
        name: "Edward Nathaniel Handoko",
        image: saphireAchievers4,
        country: ListOfCity.SRB,
        YoutubeLink: "https://www.youtube.com/watch?v=twdiVI7WYNA&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2025UPCOMING"]]
    },
    {
        name: "Jaden William Tang",
        image: saphireAchievers5,
        country: ListOfCity.PLB,
        YoutubeLink: "https://www.youtube.com/watch?v=P43e51OVkWQ&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2023CHRISTMAS"]]
    },
    {
        name: "Keenan Kwok",
        image: saphireAchievers6,
        country: ListOfCity.JKT,
        YoutubeLink: "https://www.youtube.com/watch?v=MRbkf3Jlm9I&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2025UPCOMING"]]
    },
    {
        name: "Jeffren Leliga",
        image: saphireAchievers7,
        country: ListOfCity.SRB,
        YoutubeLink: "https://www.youtube.com/watch?v=bMBKgEL4x3w&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2025UPCOMING"], ListOfEventAchiever["2023CHRISTMAS"]]
    },
    {
        name: "Charice Elleanore Konggo Budiman",
        image: saphireAchievers8,
        country: ListOfCity.SRB,
        YoutubeLink: "https://www.youtube.com/watch?v=__sIBAeIqCE&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2023CHRISTMAS"]]
    },
    {
        name: "Alf Elijah Beloved Sigarlaki",
        image: saphireAchievers9,
        country: ListOfCity.JKT,
        YoutubeLink: "https://www.youtube.com/watch?v=1sqUiE7SP30&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2025UPCOMING"], ListOfEventAchiever["2023CHRISTMAS"]]
    },
    {
        name: "Sydney Mikaela Tan",
        image: saphireAchievers10,
        country: ListOfCity.TNG,
        YoutubeLink: " https://www.youtube.com/watch?v=woQYPaBtJqM&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2022MAGICMUSIC"]]
    },
    {
        name: "Gregorius Reinhardt",
        image: saphireAchievers11,
        country: ListOfCity.PLB,
        // YoutubeLink: "https://www.youtube.com/watch?v=XR8yYVUsBzo&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2023CHRISTMAS"]]
    },
    {
        name: "Ashton Micah Poh",
        image: saphireAchievers12,
        country: ListOfCity.TNG,
        YoutubeLink: "https://youtu.be/Fv7SkBb-EKo?t=113",
        event: [ListOfEventAchiever["2022MAGICMUSIC"]]
    },
    {
        name: "Darius Tairisya",
        image: saphireAchievers13,
        country: ListOfCity.TNG,
        YoutubeLink: "https://youtu.be/mSfGrHZK4Ww?t=130",
        event: [ListOfEventAchiever["2022MAGICMUSIC"]]
    },
    {
        name: "Katherine Natalie Mulyadi",
        image: saphireAchievers14,
        country: ListOfCity.BGR,
        YoutubeLink: "https://youtu.be/apgUhkXAIVs",
        event: [ListOfEventAchiever["2022MAGICMUSIC"]]
    },
    {
        name: "Fairlyn Dharmawan",
        image: saphireAchievers15,
        country: ListOfCity.TNG,
        YoutubeLink: " https://www.youtube.com/watch?v=apgUhkXAIVs&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2022MAGICMUSIC"]]
    },
    {
        name: "Mikhayla Sofilia Widjaja",
        image: saphireAchievers16,
        country: ListOfCity.TNG,
        YoutubeLink: " https://www.youtube.com/watch?v=8pCkvjzr8RE&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2022MAGICMUSIC"]]
    },
    {
        name: "Chindy Anastasya",
        image: saphireAchievers17,
        country: ListOfCity.TNG,
        YoutubeLink: "https://www.youtube.com/watch?v=Fv7SkBb-EKo&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2022MAGICMUSIC"]]
    },
    {
        name: "Liselle Fendbee Soe",
        image: saphireAchievers18,
        country: ListOfCity.BTM,
        YoutubeLink: "https://youtu.be/8pCkvjzr8RE?t=59",
        event: [ListOfEventAchiever["2022MAGICMUSIC"]]
    },
    {
        name: "Issac Mulya Putra",
        image: saphireAchievers19,
        country: ListOfCity.TNG,
        YoutubeLink: "https://www.youtube.com/watch?v=J55IRPHgsjw&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2022MAGICMUSIC"]]
    },
    {
        name: "Pakpahan Aminan Shantlerine A.R",
        image: saphireAchievers20,
        country: ListOfCity.BKS,
        YoutubeLink: "https://www.youtube.com/watch?v=mSfGrHZK4Ww&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2022MAGICMUSIC"]]
    },
    {
        name: "Nadya Adeline Hermanto",
        image: saphireAchievers21,
        country: ListOfCity.TNG,
        YoutubeLink: ":https://www.youtube.com/watch?v=4WdAL9usTK8&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2022MAGICMUSIC"]]
    },
    {
        name: "Cheryl Pandora",
        image: saphireAchievers22,
        country: ListOfCity.MD,
        YoutubeLink: "https://www.youtube.com/watch?v=XFvWVT0Wroc&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2023CLASSICSRBY"]]
    },
    {
        name: "Ann Shereen Yao & Adrianne Shanelle Yao",
        image: saphireAchievers23,
        country: ListOfCity.JKT,
        YoutubeLink: "https://www.youtube.com/watch?v=779gXnPTs-0&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2023CLASSICJKT"]]
    },
    {
        name: "Joshua Kevin Hudyana",
        image: saphireAchievers24,
        country: ListOfCity.SRB,
        YoutubeLink: "https://www.youtube.com/watch?v=JDU_q_ZjfW0&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2023CLASSICSRBY"]]
    },
    {
        name: "Clayton Oliver Hayasi",
        image: saphireAchievers26,
        country: ListOfCity.JKT,
        YoutubeLink: "https://www.youtube.com/watch?v=Fke-4LVyGno&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2023CLASSICJKT"]]
    },
    {
        name: "Michael Phillipe Andree",
        image: saphireAchievers25,
        country: ListOfCity.SRB,
        YoutubeLink: "https://www.youtube.com/watch?v=9Xgu6PLNNg0&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2023CLASSICSRBY"]]
    },
    {
        name: "Kaleb Yuseli",
        image: saphireAchievers27,
        country: ListOfCity.SLT,
        YoutubeLink: "https://www.youtube.com/watch?v=OrQ2tsXxe6o&ab_channel=APIANOCONCERTOSERIES",
        event: [ListOfEventAchiever["2023CLASSICJKT"]]
    },

    {
        "name": "Miguela Naraya Ng",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Charlotte Theodora Chia",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Sharlyn Chandra",
        "image": "dummyimage",
        "country": ListOfCity.SRB,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "William Anthony Mulyadi",
        "image": "dummyimage",
        "country": "Bogor",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Skyler Frensi Lie ",
        "image": "dummyimage",
        "country": "Bogor",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Chloe Sinjaya",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Louis Mclawrence Hendra",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Ong Yu Xuan Alyssa",
        "image": "dummyimage",
        "country": "Singapore",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Austin Aldrich Tirta",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Candyce Eudora Oung ",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Wilson Anthony Mulyadi",
        "image": "dummyimage",
        "country": "Bogor",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Darlene Manuella Gani",
        "image": "dummyimage",
        "country": ListOfCity.SRB,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Cathleen Scarlett Hayasi",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Russell Nathan Indrali",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Freya Venezia Bong ",
        "image": "dummyimage",
        "country": ListOfCity.SRB,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Dominic Joel Wijaya",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Leticya Caithlynn Phanjaya",
        "image": "dummyimage",
        "country": "Solo",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Katherine Natalie Mulyadi",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Candice Chloe King",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Carissa Faith Anggana",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "KARIN MICHIKO PANGESTOE",
        "image": "dummyimage",
        "country": "Tangerang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Clayton Oliver Hayasi",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Michael Sudianto",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Elliot Tjendra",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Abigail Angelica Santoso",
        "image": "dummyimage",
        "country": "Solo",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Rachel Nathania Suyanto",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Gabriella Kezia Rosalind",
        "image": "dummyimage",
        "country": "Tangerang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Elliot Tjendra ",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Phoebe Fleur Widjaja",
        "image": "dummyimage",
        "country": "Semarang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Darlene Liman",
        "image": "dummyimage",
        "country": ListOfCity.SRB,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Jasmine Isabel Pesik",
        "image": "dummyimage",
        "country": "Tangerang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Kamala Kilau Pelangi",
        "image": "dummyimage",
        "country": "Semarang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Maryam Almayrha Nugraha",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Shannon Richelle Johannanto",
        "image": "dummyimage",
        "country": "Semarang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Lennart Joshua Sugih",
        "image": "dummyimage",
        "country": "Surakarta",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Clarisse Faith Hariyadi",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Leticia Mikhaela Amijaya",
        "image": "dummyimage",
        "country": "Semarang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Audi Winter Lee & Cherry Carissa Ho",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Louise Michelle Emerald Joseph",
        "image": "dummyimage",
        "country": "Semarang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Annabelle Samuela Ng",
        "image": "dummyimage",
        "country": "Tangerang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Jovie Peng",
        "image": "dummyimage",
        "country": "Pontianak",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Braelynn Love Suryaatmadja",
        "image": "dummyimage",
        "country": "Semarang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Cherry Carissa Ho",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Audi Winter Lee",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Celine Gabriella Amijaya",
        "image": "dummyimage",
        "country": "Semarang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Abigail Caitlyn Electra",
        "image": "dummyimage",
        "country": "Semarang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Khellse Valerine",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Vanessa Christy Kurniawan",
        "image": "dummyimage",
        "country": "Semarang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Joline Abigail Iskandar",
        "image": "dummyimage",
        "country": ListOfCity.SRB,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Keiko Sheravine Cen",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Shane Keegan Cen",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Calya Anara Wijaya",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Michael Phillipe Andree",
        "image": "dummyimage",
        "country": ListOfCity.SRB,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Naomi Thelma",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Naomi Kaitlyn",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Floriana Hoei",
        "image": "dummyimage",
        "country": "Tangerang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Milka Kalyana Setiawan",
        "image": "dummyimage",
        "country": "Tangerang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Jordan Eli Santoso",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Kimberly Della Sophie Hutapea ",
        "image": "dummyimage",
        "country": "Tangerang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Rachel Untoro",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Lionel Nathan Wijaya ",
        "image": "dummyimage",
        "country": "Tangerang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Jocelyn Angelica Wicaksono",
        "image": "dummyimage",
        "country": "Semarang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Keiko William",
        "image": "dummyimage",
        "country": "Tangerang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Madelynn Esmee Theodore ",
        "image": "dummyimage",
        "country": ListOfCity.SRB,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Charlene Ariana Sukri",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Prapta Dimatteo Pratama",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Leonard Sterling Tanoko",
        "image": "dummyimage",
        "country": "Malang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Kenzo Lionel Hendry",
        "image": "dummyimage",
        "country": "Palembang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Valerie Edyana Wibianto",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Jonathan Sugiharto Iskandar",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Ritchie Jaimeson Kowara",
        "image": "dummyimage",
        "country": "Palembang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Valerie Edyana Wibianto",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Audrey Winna Yohan",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Leonard Sterling Tanoko",
        "image": "dummyimage",
        "country": "Malang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Jorge Amadeo Benavides",
        "image": "dummyimage",
        "country": "Surakarta",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Jelica Angelline Zecy Yang",
        "image": "dummyimage",
        "country": "Jambi",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Cleo Alexis Sudarman",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Maximus Huang Tirtawigoena ",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Catherine Emilianna Chahyadi",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Alberta Debora Alva Kambuno ",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Carole Valerie Gunawan",
        "image": "dummyimage",
        "country": ListOfCity.SRB,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Claire Audrey Sudarman",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Serene Patricia",
        "image": "dummyimage",
        "country": ListOfCity.SRB,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Marta Liauw",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Domi Satria",
        "image": "dummyimage",
        "country": "Yogyakarta",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Clarissa Abigail Pradana",
        "image": "dummyimage",
        "country": "Bali",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Meghan Alisa Wu",
        "image": "dummyimage",
        "country": "Bali",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Kanaya Namirah Cetta",
        "image": "dummyimage",
        "country": "Palembang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Chelsea Joanna Setiawan",
        "image": "dummyimage",
        "country": "Yogyakarta",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Parrish Lim",
        "image": "dummyimage",
        "country": "Palembang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "GWYNETH ALICIA PRADANA",
        "image": "dummyimage",
        "country": "Bali",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Afonso Rufino Abilio de Araujo",
        "image": "dummyimage",
        "country": "Jkt",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Jocelyn Gabrielle Alexander",
        "image": "dummyimage",
        "country": "Palembang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Gwyneth Madeline Liechelle Fanto",
        "image": "dummyimage",
        "country": "Yogyakarta",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Josephine Gabrielle Alexander",
        "image": "dummyimage",
        "country": "Palembang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Gwen Sabriela Nugroho",
        "image": "dummyimage",
        "country": "Yogyakarta",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Gizelle Everly Wantana",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Matthew Joshua Elnathan",
        "image": "dummyimage",
        "country": "Yogyakarta",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Nataren Velice ",
        "image": "dummyimage",
        "country": "Palembang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Mikaela Devanova Amara Belva",
        "image": "dummyimage",
        "country": "Yogyakarta",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Pauline Lim",
        "image": "dummyimage",
        "country": "Palembang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Gwyneth Madeline Liechelle Fanto & Melodi Tirza",
        "image": "dummyimage",
        "country": "Yogyakarta",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Lorraine Anastasia Salim",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Giuliana Victoria Santosa",
        "image": "dummyimage",
        "country": "Yogyakarta",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Athanasius Warren Jonatan",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Aurelia Lovely Bessie",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Maria Olivia Christabel Elnathan",
        "image": "dummyimage",
        "country": "Yogyakarta",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Kabhinawa Luh Cintamani Adyutakara",
        "image": "dummyimage",
        "country": "Yogyakarta",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Sam Joseph Arthur",
        "image": "dummyimage",
        "country": "Semarang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Cathlyn Pherone Chandra",
        "image": "dummyimage",
        "country": "Palembang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Matthew Kenzo Alexander",
        "image": "dummyimage",
        "country": "Bali",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Kimberly Rachel Gu",
        "image": "dummyimage",
        "country": "Tangerang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Arissa Eillin Budiono",
        "image": "dummyimage",
        "country": "Palembang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Cleo Alexis Sudarman & Keiko Sheravine Cen",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Giselle Naeva Gozali & Michelle Naeva Gozali",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Elijah Javier Soetanto",
        "image": "dummyimage",
        "country": "Palembang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Callia Kardiono",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Emma Joy Soetanto ",
        "image": "dummyimage",
        "country": "Palembang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Claire Hartono",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Faith Huang",
        "image": "dummyimage",
        "country": ListOfCity.SRB,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Debee Chan",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Callista Vanesa",
        "image": "dummyimage",
        "country": "Lampung",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Hillary Howie Lymnois",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Freya Calista Suhandi",
        "image": "dummyimage",
        "country": "Lampung",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Charice Elleanore Konggo Budiman",
        "image": "dummyimage",
        "country": ListOfCity.SRB,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Skye Hartono",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Cornelius Carlton Chandra",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Naomi Thelma & Edward Chandra ",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Christabel Estelle Oei ",
        "image": "dummyimage",
        "country": "Palembang",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Michelle Sutanto",
        "image": "dummyimage",
        "country": "Pekanbaru",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Jorel Aviello",
        "image": "dummyimage",
        "country": ListOfCity.JKT,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Trisha Juwono Leung",
        "image": "dummyimage",
        "country": "Pekanbaru",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Hillary Howie Lymnois & Debee Chan",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Claire Audrey Sudarman & Cornelius Carlton Chandra",
        "image": "dummyimage",
        "country": "Medan",
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    },
    {
        "name": "Cheryn Pandora & Edenia Maureen",
        "image": "dummyimage",
        "country": ListOfCity.SRB,
        "YoutubeLink": "https://www.youtube.com/@apcsmusic",
        "event": [ListOfEventAchiever["2024APCSCLASSIC"]],
    }
];